### ISSUE TITLE
dev/ttyAMA0 not showing

### ISSUE THREAD

**Issue by xiki808** [codm/cc2652-raspberry-pi-module#2]
Hi! I'm quite new to these type of configurations, and I'm sure I'm missing something. 

I am running Debian 11 on my raspberry pi downloaded from here: https://raspi.debian.net/tested-images/

I have SSH access to my pi, I created config.txt in /boot directory with the following contents:

```
dtoverlay=miniuart-bt
enable_uart=1
```

When I restart my pi I cannot find /dev/ttyAMA0.

Also what should be the header configuration? Should I just take that off? 

Thank you!

**Comment by xiki808** [comment]
Thank you for your reply, I'm using Pi 4.

Thank your for the link! .. But I'm still at a loss :/

With the header configuration I meant the 2x05 header, as mentioned in the readme, under JTAG. Is this only needed, and thus plugged on the chip only when a firmware update is needed? At the moment I have it removed.

**Comment by codmpm** [comment]
Jo mostly won't need to do anything with the JTAG headers.

Here's the config from my test-Pi (Pi4):

`/boot/config.txt`
```
enable_uart=1
dtoverlay=disable-bt
```

`/boot/cmdline.txt`
```
dwc_otg.lpm_enable=0 console=tty1 root=PARTUUID=80bd3ba5-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
```

Please check if you have the settings accordingly. Of course don't copy any UUID or something. Just adjust your settings to match.

After that `/dev/ttyAMA0` should be visible.
Maybe check `raspi-config` and enable UART there.

**Comment by xiki808** [comment]
I am in the right directory, I'm afraid the clash can be due to running Debian 11 rather than Rasbian. Even cmdline.txt is missing in my case. I'll try out what you sent.

**Comment by xiki808** [comment]
This is what I currently have, not sure but maybe you can spot something weird..

![image](https://user-images.githubusercontent.com/8024321/131856884-dd7bce8b-eb6c-4957-b633-632834c123f0.png)

**Comment by codmpm** [comment]
Try `/dev/ttyS0`- but no guaranty. I did not do anything with debian on the Pi, yet.
Maybe you can use raspbian to see if eversthing works otherwise.

Also you could check where the Pi UARTs reside on a debian installation.

**Comment by xiki808** [comment]
Switched to rasbian and it worked with no probs
