### ISSUE TITLE
Cannot flash firmware with cc2538-prog

### ISSUE THREAD

**Issue by linosteenkamp** [codm/cc2652-raspberry-pi-module#4]
Downloaded and compiled cc2538-prog on the raspberry pi

Downloaded and unzipped CC1352P2_CC2652P_launchpad_coordinator_20210708.zip

enabled the bootloader as instructed

Executing the following command: 
$ ./cc2538-prog -d /dev/ttyAMA0 -f CC1352P2_CC2652P_launchpad_coordinator_20210708.hex

It starts running but then fails. See the shortened output. 

Any idea as to what I'm doing wrong?

ping ok
Bootloader detected
Erasing page 0
Erasing page 1
.
.
Writing 32 bytes to 0x00002080
Writing 32 bytes to 0x000020A0
serialread byte failed
send_data failed
send_data failed
Failed to read CC1352P2_CC2652P_launchpad_coordinator_20210708.hex

Have tried two different CC1352P2_CC2652P_launchpad_coordinator_20210708.hex files. One unzipped on a Mac and SCPd and one locally downloaded and unzipped.

**Comment by codmpm** [comment]
Hmm,

you did everything correct, as it seams.
See https://github.com/codm/cc2652-raspberry-pi-module#serial-via-gpio - should be ok.

Do you have a stable power source? Maybe change the power supply (quick shot).
Otherwise you can try https://github.com/JelmerT/cc2538-bsl

Sorry, did not see this error, yet.

**Comment by linosteenkamp** [comment]
@codmpm Thank you for the quick reply.

Tried with a different power supply, no luck.

Moved the board to a pi zero and flashed it there without any issue.

Not sure why this is happening on the Pi 4

**Comment by codmpm** [comment]
Had no issues on a Pi4 so far.
But glad it works now.
